### ISSUE TITLE
Error while installing spicecrm-master

### ISSUE THREAD

**Issue by Kameshwarsingh** [spicecrm/spicecrm#3]
I get below error and installation fails. I am using Apache 2.4, PHP 7.x, Can anyone please help to resolve.

Uncaught Error: Cannot use string offset as an array in C:\installs\software\Apache24\htdocs\spicecrm-master\modules\Cases\vardefs.php:264 Stack trace: #0 C:\installs\software\Apache24\htdocs\spicecrm-master\data\SugarBean.php(812): include() #1 C:\installs\software\Apache24\htdocs\spicecrm-master\install\performSetup.php(254): SugarBean::createRelationshipMeta('Case', Object(MysqliManager), 'cases', 'A', 'Cases') #2 C:\installs\software\Apache24\htdocs\spicecrm-master\install.php(615): require('C:\\installs\\sof...') #3 {main} thrown in C:\installs\software\Apache24\htdocs\spicecrm-master\modules\Cases\vardefs.php on line 264

**Comment by maretval** [comment]
Installation runs perfectly under my apache 2.4 php 7.0.4 environment.
1) Can you tell me the exact php7 version you have in use? 
2) After which step you get the error?
) Choose language
) Are you ready to installation
) License Acceptance
) Select Typical Install | Custom Install
) Specify Database Type 
) provide database connection data, select demo data
) Identify Administration User
) in case of custom install: Select Security Options
) Confirm Settings
) Click Install
) Installation complete
) in case of custom install: add language pack

3) Do you have any errors in "Confirm Settings"?

**Comment by Kameshwarsingh** [comment]
I faced above issue with PHP 7.1 (Windows 64).   I came to know from few post/documentation that in PHP 7.1 there is change in syntax of referring arrays/string, so I installed PHP 7.0, now it works fine.

**Comment by maretval** [comment]
thank you for using this workaround, we will adapt the code for php7.1 in a future release.
