### ISSUE TITLE
PostgreSQL support does not work

### ISSUE THREAD

**Issue by opravil-jan** [spicecrm/spicecrm#5]
Hello, 

I tried install spicecrm on PostgreSQL and I got this error:

Wed Nov  1 06:55:02 2017 [26252][-none-][FATAL]  Query Failed:SELECT * FROM spicebeanguides::: PgSQL error ERROR:  relation "spicebeanguides" does not exist
LINE 1: SELECT * FROM spicebeanguides
                      ^
Wed Nov  1 06:55:02 2017 [26252][-none-][FATAL]  Query Failed:SELECT id FROM outbound_email WHERE type = 'system'::: PgSQL error ERROR:  relation "outbound_email" does not exist
LINE 1: SELECT id FROM outbound_email WHERE type = 'system'
                       ^
Wed Nov  1 06:55:02 2017 [26252][-none-][FATAL]  Query Failed:INSERT INTO outbound_email (id,name,type,user_id,mail_sendtype,mail_smtptype,mail_smtpserver,mail_smtpport,mail_smtpuser,mail_smtppass,mail_smtpauth_req,mail_smtpssl) VALUES ('2167d62a-a636-a3ff-b13d-59f961940f13','system','system','1','SMTP','other','',25,'','',1,0)::: PgSQL error ERROR:  relation "outbound_email" does not exist
LINE 1: INSERT INTO outbound_email (id,name,type,user_id,mail_sendty...
                    ^
Wed Nov  1 06:56:01 2017 [26428][-none-][FATAL] Configuration variable date.timezone is not set, guessed timezone Europe/Berlin. Please set date.timezone="Europe/Berlin" in php.ini!
Wed Nov  1 06:56:01 2017 [26428][-none-][FATAL]  Query Failed:SELECT * FROM spicebeanguides::: PgSQL error ERROR:  relation "spicebeanguides" does not exist
LINE 1: SELECT * FROM spicebeanguides
                      ^
Wed Nov  1 06:56:01 2017 [26428][-none-][FATAL]  Query Failed:SELECT id FROM outbound_email WHERE type = 'system'::: PgSQL error ERROR:  relation "outbound_email" does not exist
LINE 1: SELECT id FROM outbound_email WHERE type = 'system'
                       ^
Wed Nov  1 06:56:01 2017 [26428][-none-][FATAL]  Query Failed:INSERT INTO outbound_email (id,name,type,user_id,mail_sendtype,mail_smtptype,mail_smtpserver,mail_smtpport,mail_smtpuser,mail_smtppass,mail_smtpauth_req,mail_smtpssl) VALUES ('a3f922a7-043e-f23f-275c-59f961441a6c','system','system','1','SMTP','other','',25,'','',1,0)::: PgSQL error ERROR:  relation "outbound_email" does not exist
LINE 1: INSERT INTO outbound_email (id,name,type,user_id,mail_sendty...
                    ^
Wed Nov  1 06:56:05 2017 [24655][-none-][FATAL] Error creating table: competitorassessments: Query Failed:CREATE INDEX idx_opp ON competitorassessments (opportunity_id);::: PgSQL error ERROR:  relation "idx_opp" already exists

**Comment by maretval** [comment]
Fix will be implemented for Winter release in December 2017

**Comment by maretval** [comment]
PostgreSQL abandoned for now
