### ISSUE TITLE
Not Passing licence Acceptance Page

### ISSUE THREAD

**Issue by sgatibaru** [spicecrm/spicecrm#6]
I can't seem to pass the licence acceptance page. I thought it was an issue with my current browser (Chrome) but attempts with Firefox are also stuck at this page. What could be the issue?

**Comment by maretval** [comment]
Which PHP Version is installed on your server? Current release supports 7.0.
The coming one (scheduled this month) will support 7.1
Please check your php error log. It should contain some clues.

**Comment by allenjd** [comment]
Just encountered this issue. Found the following in the Apache error log:

> [Wed Oct 03 10:31:03.700180 2018] [core:error] [pid 23590] (13)Permission denied: [client 129.173.67.8:55380] AH00035: access to /cache/include/javascript/sugar_grp1_yui.js denied (filesystem path '/local/data/spicecrm/cache/include') because search permissions are missing on a component of the path, referer: http://spice.research.cs.dal.ca/install.php

The filesystem permissions on /local/data/spicecrm/cache were set to 0744. Changing them to 0755 resolved the issue. The cache directory is owned by the user configured to run PHP scripts in the PHP-FPM config. Presumably, the Apache user account must be trying to serve the JavaScript file outside of a PHP request so it needs search permission to find the file. If one was using mod_php and everything was owned by Apache then it wouldn't a problem.

@sgatibaru were you using PHP-FPM?
