### ISSUE TITLE
REST API version 

### ISSUE THREAD

**Issue by yathit** [spicecrm/spicecrm#8]
As a third party REST API consumer of SugarCRM, I use `get_server_info` method in public (no auth require) REST API before using it. It returns `sugar_version.json` object having `sugar_version` fields in semantic version string something like `6.5.1`. Since *SpiceCRM* version return `2018.01.00`, usual logic to infer version to REST API version does not work. 

Do you have any suggestion to infer SpiceCRM version to its REST API version, similar to [SugarCRM version table](http://support.sugarcrm.com/Documentation/Sugar_Developer/Sugar_Developer_Guide_6.5/Application_Framework/Web_Services/Versioning/).

**Comment by maretval** [comment]
I am not sure I can follow you. Why do need to infer version? 
SpiceCRM has its own REST API called KREST by the way.

**Comment by yathit** [comment]
> Why do need to infer version?

To get correct API endpoint, e.g: I will call `service/v4_1/rest.php` for version 6.4 or `service/v4/rest.php` for version 6.2 and above.

I see. Do you have API doc for KREST?

**Comment by maretval** [comment]
We started a documentation which you can find under https://spicecrm.gitbooks.io/krest/content/
You will find the basics => how to authenticate and retrieve / save a record.
